### ISSUE TITLE
SRS progress tracking

### ISSUE THREAD

**Issue by b-wyss** [snurby7/SoftwareEngineering#11]
- [ ] 1-introduction
- [ ] 2-Overall Description
- [x] 3-Product Perspective
- [ ] 4-Product Functions
- [x] 5-User Characteristics
- [ ] 6-Constraints
- [ ] 7-Assumptions and Dependencies
- [ ] 8-Apportioning of Requirements
- [ ] 9-Specific Requirements
- [ ] 10-Modeling Requirements
- [ ] 11-Prototype
- [x] 12-How to Run Prototype
- [ ] 13-Sample Scenarios
- [ ] 14-References
- [x] 15-Point of Contact
